CREATE TABLE IF NOT EXISTS mock_incident (
    source_incident_id VARCHAR(36) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(24) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_mock_incident_status CHECK (status IN ('READY', 'IMPORTED'))
);

CREATE TABLE IF NOT EXISTS mock_missing_person (
    source_incident_id VARCHAR(36) PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL,
    photo_object_key VARCHAR(255),
    appearance_text TEXT,
    last_seen_location_text TEXT,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_mock_missing_person_incident
        FOREIGN KEY (source_incident_id)
        REFERENCES mock_incident(source_incident_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mock_assignment (
    external_assignment_key VARCHAR(160) PRIMARY KEY,
    source_incident_id VARCHAR(36) NOT NULL,
    account_code VARCHAR(80) NOT NULL,
    incident_role VARCHAR(40) NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mock_assignment_incident
        FOREIGN KEY (source_incident_id)
        REFERENCES mock_incident(source_incident_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mock_assignment_incident
    ON mock_assignment(source_incident_id);

CREATE TABLE IF NOT EXISTS mock_seed_marker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_incident_id VARCHAR(36) NOT NULL,
    type VARCHAR(40) NOT NULL,
    source VARCHAR(40) NOT NULL,
    memo TEXT,
    lon DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT fk_mock_seed_marker_incident
        FOREIGN KEY (source_incident_id)
        REFERENCES mock_incident(source_incident_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mock_seed_marker_incident
    ON mock_seed_marker(source_incident_id, sort_order);
