#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
TOTAL_MINUTES=8

OPS_DIR=/srv/ops
ENV_FILE="$OPS_DIR/.env"
BASE_COMPOSE_FILE="$OPS_DIR/docker-compose.yml"
RENDERER_COMPOSE_FILE="$OPS_DIR/docker-compose.image-renderer.yml"
RENDER_SCRIPT="$OPS_DIR/render-load-test-dashboard.sh"
GRAFANA_URL=https://grafana.sonic8-8.com
umask 077

die() {
  warn "$1"
  exit 1
}

banner "Grafana image rendering setup"

stage "Ops server preflight" 1
for command_name in docker curl openssl; do
  command -v "$command_name" >/dev/null 2>&1 || die "required command not found: $command_name"
done
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required"
for required_file in "$BASE_COMPOSE_FILE" "$RENDERER_COMPOSE_FILE" "$RENDER_SCRIPT"; do
  [[ -f "$required_file" ]] || die "required file not found: $required_file"
done
[[ -x "$RENDER_SCRIPT" ]] || die "render script is not executable: $RENDER_SCRIPT"
touch "$ENV_FILE" || die "cannot write $ENV_FILE; run this wizard with sudo"
chmod 600 "$ENV_FILE"
say "Preflight passed. Secrets will stay in $ENV_FILE."
pause "Press Enter to create the Grafana service account."

stage "Grafana Viewer service account" 4
say "Create a dedicated Viewer account for automated dashboard rendering."
open_url "$GRAFANA_URL/org/serviceaccounts"
step "Sign in through Nginx and Grafana if prompted."
step "Open Administration → Users and access → Service accounts."
step "Create 'load-test-renderer' with the Viewer role, or open it if it already exists."
step "If no token is saved yet, add 'dashboard-renderer' and copy it. Leave expiration empty for this server-only automation token."
ask_secret GRAFANA_RENDER_SERVICE_ACCOUNT_TOKEN "Paste the service account token:"
[[ -n "$GRAFANA_RENDER_SERVICE_ACCOUNT_TOKEN" ]] || die "the service account token cannot be empty"

AUTH_HEADER_FILE=$(mktemp)
printf 'Authorization: Bearer %s\n' "$GRAFANA_RENDER_SERVICE_ACCOUNT_TOKEN" > "$AUTH_HEADER_FILE"
if ! curl --fail --silent --show-error \
  --header "@$AUTH_HEADER_FILE" \
  'http://127.0.0.1:3000/api/access-control/user/permissions' >/dev/null; then
  rm -f -- "$AUTH_HEADER_FILE"
  die "Grafana rejected the service account token"
fi
rm -f -- "$AUTH_HEADER_FILE"
write_env GRAFANA_RENDER_SERVICE_ACCOUNT_TOKEN "$GRAFANA_RENDER_SERVICE_ACCOUNT_TOKEN"

GRAFANA_RENDERER_TOKEN=$(_existing GRAFANA_RENDERER_TOKEN || true)
if [[ -z "$GRAFANA_RENDERER_TOKEN" ]]; then
  GRAFANA_RENDERER_TOKEN=$(openssl rand -hex 32)
  write_env GRAFANA_RENDERER_TOKEN "$GRAFANA_RENDERER_TOKEN"
else
  note "keeping the existing GRAFANA_RENDERER_TOKEN"
fi
chmod 600 "$ENV_FILE"

stage "Apply and verify" 3
say "Grafana will be recreated once with the renderer URL and shared token."
if ! confirm "Recreate only the Grafana container now?"; then
  SKIPPED+=("Grafana renderer configuration: re-run this wizard when a restart is acceptable")
  finish
  exit 0
fi

COMPOSE=(
  docker compose
  --env-file "$ENV_FILE"
  -f "$BASE_COMPOSE_FILE"
  -f "$RENDERER_COMPOSE_FILE"
)
"${COMPOSE[@]}" config >/dev/null
"${COMPOSE[@]}" up -d --no-deps grafana

GRAFANA_READY=false
for _ in {1..30}; do
  if curl --fail --silent 'http://127.0.0.1:3000/api/health' >/dev/null; then
    GRAFANA_READY=true
    break
  fi
  sleep 1
done
[[ "$GRAFANA_READY" == true ]] || die "Grafana did not become ready within 30 seconds"

SMOKE_PNG=$(mktemp --suffix=.png)
if ! "$RENDER_SCRIPT" \
  453 \
  2026-09-01T03:48:30Z \
  2026-09-01T03:56:30Z \
  "$SMOKE_PNG"; then
  rm -f -- "$SMOKE_PNG"
  die "dashboard rendering failed"
fi
rm -f -- "$SMOKE_PNG"
say "Renderer smoke test passed and the on-demand renderer is stopped."

finish
