ALTER TABLE police_phone
    ADD COLUMN IF NOT EXISTS registered BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE police_phone
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE refresh_token
    ADD COLUMN IF NOT EXISTS channel VARCHAR(16) NOT NULL DEFAULT 'APP';

ALTER TABLE refresh_token
    ALTER COLUMN channel DROP DEFAULT;
