import type { IncidentCard, IncidentFilter } from '../types/incidentList';

export const INCIDENT_FILTERS: IncidentFilter[] = ['전체', '진행 중', '인계 대기', '종료'];

export const INCIDENT_LIST_PAGE_SIZE = 12;

export const mockIncidentList: IncidentCard[] = [
  {
    id: 'INC-2026-0506-001',
    title: '김OO · 73세 남 · 실종 사건',
    status: '진행 중',
    location: '광주 북구 두암동',
    timeKind: '마지막 목격',
    timeLabel: '오늘 08:12',
    currentPhase: 'OP 3차 · 재수색',
    assignedOrganization: '실종팀 1팀',
    assignedTeam: '광주북부서 기동3부대',
  },
  {
    id: 'INC-2026-0506-002',
    title: '박OO · 64세 여 · 가출 추정',
    status: '진행 중',
    location: '시흥시 매화동',
    timeKind: '신고 시각',
    timeLabel: '오늘 07:40',
    currentPhase: 'OP 2차 · 수색 범위 확장',
    assignedOrganization: '실종팀 2팀',
    assignedTeam: '매화지구대 당직팀',
  },
  {
    id: 'INC-2026-0505-003',
    title: '최OO · 78세 남 · 치매 의심',
    status: '인계 대기',
    location: '광주 동구 학동',
    timeKind: '갱신 시각',
    timeLabel: '오늘 09:05',
    currentPhase: 'OP 1차 · 구역 분할 중',
    assignedOrganization: '실종팀 1팀',
    assignedTeam: '광주동부서 순찰차 12호',
  },
  {
    id: 'INC-2026-0505-004',
    title: '정OO · 16세 남 · 미귀가',
    status: '진행 중',
    location: '광주 서구 화정동',
    timeKind: '마지막 목격',
    timeLabel: '어제 22:18',
    currentPhase: 'OP 4차 · 경로 재확인',
    assignedOrganization: '실종팀 3팀',
    assignedTeam: '광주서부서 기동1부대',
  },
  {
    id: 'INC-2026-0504-005',
    title: '이OO · 82세 여 · 실종 사건',
    status: '종료',
    location: '광주 남구 봉선동',
    timeKind: '갱신 시각',
    timeLabel: '어제 18:30',
    currentPhase: '파기 진행 · 종료',
    assignedOrganization: '실종팀 1팀',
    assignedTeam: '광주남부서 기동2부대',
  },
  {
    id: 'INC-2026-0504-006',
    title: '한OO · 54세 남 · 실종 사건',
    status: '진행 중',
    location: '광주 광산구 수완동',
    timeKind: '신고 시각',
    timeLabel: '어제 21:05',
    currentPhase: 'OP 2차 · 현장 확인',
    assignedOrganization: '실종팀 2팀',
    assignedTeam: '수완지구대 순찰차 03호',
  },
  {
    id: 'INC-2026-0503-007',
    title: '송OO · 67세 여 · 치매 의심',
    status: '인계 대기',
    location: '시흥시 배곧동',
    timeKind: '마지막 목격',
    timeLabel: '어제 20:12',
    currentPhase: 'OP 1차 · 메모 정리',
    assignedOrganization: '실종팀 4팀',
    assignedTeam: '배곧지구대 당직팀',
  },
  {
    id: 'INC-2026-0503-008',
    title: '윤OO · 11세 남 · 미귀가',
    status: '진행 중',
    location: '광주 북구 운암동',
    timeKind: '신고 시각',
    timeLabel: '어제 19:48',
    currentPhase: 'OP 5차 · 단서 확인',
    assignedOrganization: '실종팀 2팀',
    assignedTeam: '광주북부서 기동2부대',
  },
  {
    id: 'INC-2026-0502-009',
    title: '장OO · 70세 남 · 실종 사건',
    status: '종료',
    location: '광주 동구 지원동',
    timeKind: '갱신 시각',
    timeLabel: '5월 2일 17:20',
    currentPhase: '종료 · 기록 보관',
    assignedOrganization: '실종팀 3팀',
    assignedTeam: '광주동부서 순찰차 07호',
  },
  {
    id: 'INC-2026-0502-010',
    title: '서OO · 59세 여 · 실종 사건',
    status: '진행 중',
    location: '시흥시 정왕동',
    timeKind: '마지막 목격',
    timeLabel: '5월 2일 16:10',
    currentPhase: 'OP 2차 · 차량 구간 확인',
    assignedOrganization: '실종팀 1팀',
    assignedTeam: '정왕지구대 순찰차 08호',
  },
  {
    id: 'INC-2026-0501-011',
    title: '오OO · 76세 남 · 실종 사건',
    status: '종료',
    location: '광주 서구 상무동',
    timeKind: '갱신 시각',
    timeLabel: '5월 1일 14:55',
    currentPhase: '파기 완료',
    assignedOrganization: '실종팀 2팀',
    assignedTeam: '광주서부서 기동4부대',
  },
  {
    id: 'INC-2026-0501-012',
    title: '조OO · 43세 남 · 장기 미귀가',
    status: '진행 중',
    location: '광주 남구 진월동',
    timeKind: '신고 시각',
    timeLabel: '5월 1일 09:30',
    currentPhase: 'OP 1차 · 초기 수색',
    assignedOrganization: '실종팀 4팀',
    assignedTeam: '진월지구대 당직팀',
  },
  {
    id: 'INC-2026-0430-013',
    title: '배OO · 66세 여 · 실종 사건',
    status: '인계 대기',
    location: '시흥시 월곶동',
    timeKind: '마지막 목격',
    timeLabel: '4월 30일 20:40',
    currentPhase: 'OP 3차 · 인계 메모 정리',
    assignedOrganization: '실종팀 3팀',
    assignedTeam: '월곶지구대 순찰차 05호',
  },
  {
    id: 'INC-2026-0430-014',
    title: '유OO · 88세 남 · 실종 사건',
    status: '종료',
    location: '광주 북구 용봉동',
    timeKind: '갱신 시각',
    timeLabel: '4월 30일 11:15',
    currentPhase: '종료 · 파기 대기',
    assignedOrganization: '실종팀 1팀',
    assignedTeam: '광주북부서 기동1부대',
  },
  {
    id: 'INC-2026-0429-015',
    title: '노OO · 29세 남 · 실종 사건',
    status: '진행 중',
    location: '광주 광산구 첨단동',
    timeKind: '신고 시각',
    timeLabel: '4월 29일 23:05',
    currentPhase: 'OP 2차 · 구역 확인',
    assignedOrganization: '실종팀 2팀',
    assignedTeam: '첨단지구대 당직팀',
  },
];
